### PR TITLE
Use temporary files as output JS files

### PR DESCRIPTION
**Pull request by Double-oxygeN**

### CODE REVIEW

**Comment by bmollot** [comment]
Hey. I'm not interested in maintaining this. If you'd like I can transfer ownership to you.

**Comment by Double-oxygeN** [comment]
I can accept it if you send a request.

**Comment by bmollot** [comment]
The transfer won't work so long as you already have a repo called "nim-loader".

**Comment by Double-oxygeN** [comment]
Okay, I deleted the repo.

**Comment by Double-oxygeN** [comment]
@idle-z Could you transfer the npm package to me? My npm username is ``labguns``.

[Transferring a package from a user account to another user account | npm Docs](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account)

**Pull request closed without merging**
